version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/usr/src/app
      - ./data:/data  # Assuming you want to persist data across container restarts
